project_id = "nvdismuuoimdlcjcjbih"

[functions.ai-search]
verify_jwt = true

[functions.draft-assistant]
verify_jwt = true

[functions.admin-auth]
verify_jwt = false

[functions.legal-chat]
verify_jwt = true